# Use official MySQL image
FROM mysql:8.0

# Set MySQL root password and create a database
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=my_db
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=pass

# Expose MySQL default port
EXPOSE 3306
